---
title: "DATA534 Progress Notebook"
author: "Edmundson, Jonah"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true 
    toc_depth: 3
    toc_float: true
    number_sections: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

As per the project requirements:

> Document and report daily your job in your own github repo for the assignment

### Prior to Jan 17

Set up CI with GitHub Actions. 


### Jan 17

Stayed up way too late trying to figure out valid ways to query the API. Found and read documentation. 


### Jan 19

Lots of setup today. I created a whole bunch of files (ie. `code_of_conduct.md`, `contributions_workflow.md`, `LISENCE`, etc.) and organized the repo. Read tutorials on how to make a package in R. I also started working on the `README.md` file. Talked with the group about branches and merge conflicts. 


### Jan 20

Spent 2 hours troubleshooting unit testing and code coverage in R, since I haven't done this before. 


### Jan 24 

Spent the class time working on retrieving the country codes using the API. 

### Jan 25

Worked for 2.5 hours figuring out how to parse HTML/XML in R. Made a function that webscrapes search function to return first page of product names and numbers for a certain search term. 

Worked for another hour later this same day to make some more functions that prompt the user (very pretty). Also spent time trying to figure out how to properly install our own package in order to use/test the functions I made.


### Jan 26

Spent the class time (90 mins) writing unit tests and doing error handling for the functions I wrote on previous days.

On this same day, I also spent another 90 mins during lab figuring out vignettes, as well as doing some editing of the functions. 


### Jan 30

45 mins adding inline comments, some more error handling, and merging with main! :)


### Feb 1-5

Spent a bit of time here and there helping members debug stuff, I don't remember when or for how long. 



### Feb 6

Presentation practice with the group.





